/**
 * The design system, enforced instead of documented.
 *
 * WHY THIS EXISTS, AND WHY IT IS A RATCHET RATHER THAN A WALL
 * ──────────────────────────────────────────────────────────
 * `docs/research/UI-SPEC.md` §B2 asks for this file and it was never written.
 * The consequence is measurable rather than theoretical: the specification
 * defines an eight-step type scale spanning 9x, and 82% of the app's type sits
 * in the bottom three steps inside a 1.28x range. Everything is a caption. That
 * is the mechanical reason the panels read as simultaneously cluttered and
 * empty - at label size nothing can be primary, so hierarchy has to be faked
 * with uppercase and letterspacing, and half the visible text ends up wearing a
 * treatment that means "this is a label".
 *
 * A gate that failed on all of that today would fail on the first run, and a
 * gate that fails on the first run gets deleted - this repo has already deleted
 * three for exactly that. So the rules split in two:
 *
 *   HARD    things already clean. Any reintroduction is a regression and fails.
 *   RATCHET things carrying real debt. The count is recorded; it may fall and
 *           may not rise. The debt is visible in the output every run, which is
 *           what makes it get paid down instead of forgotten.
 *
 * A ratchet is not a lower standard. It is the same standard with a direction,
 * and it is the only shape that survives contact with an existing codebase.
 *
 * Run: node scripts/check-ui-tokens.ts
 */
import assert from 'node:assert/strict';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

const SRC = new URL('../src/', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');

/** Every source file under `src/`, as a path relative to it, using '/' throughout. */
function sourceFiles(dir: string, prefix = ''): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = prefix === '' ? entry : `${prefix}/${entry}`;
    if (statSync(full).isDirectory()) out.push(...sourceFiles(full, rel));
    else if (/\.(ts|tsx|css)$/.test(entry)) out.push(rel);
  }
  return out;
}

const FILES = sourceFiles(SRC).map((rel) => ({ rel, body: readFileSync(join(SRC, rel), 'utf8') }));

let failures = 0;
const report: string[] = [];

function hard(name: string, hits: readonly string[], why: string): void {
  if (hits.length === 0) {
    report.push(`  ok    ${name}`);
    return;
  }
  failures += 1;
  report.push(`  FAIL  ${name} - ${why}`);
  for (const h of hits.slice(0, 6)) report.push(`          ${h}`);
  if (hits.length > 6) report.push(`          ...and ${String(hits.length - 6)} more`);
}

/**
 * A count that may fall and may not rise.
 *
 * The baseline is written here rather than to a file on purpose: a baseline in
 * a generated file gets regenerated by whoever is annoyed by the failure, which
 * turns the ratchet back into a wall with extra steps. In source, lowering it
 * is a diff somebody reviews.
 */
function ratchet(name: string, count: number, baseline: number, why: string): void {
  if (count > baseline) {
    failures += 1;
    report.push(`  FAIL  ${name} - ${String(count)} now, ${String(baseline)} allowed. ${why}`);
  } else if (count < baseline) {
    report.push(`  ok    ${name} - ${String(count)}, down from ${String(baseline)}. Lower the baseline in this file.`);
  } else {
    report.push(`  ok    ${name} - ${String(count)}, unchanged. ${why}`);
  }
}

/* ------------------------------------------------------------------ hard */

// U16: the licence does not permit shipping it. Zero today, and must stay zero.
hard(
  'no Ailerons reference anywhere',
  FILES.filter((f) => f.body.includes('Ailerons')).map((f) => f.rel),
  'the face is not licensed for this use',
);

/*
 * Colour comes from tokens, so a theme can move it.
 *
 * `Backdrop.tsx` is the one exception and it is a real one: those literals are
 * GLSL uniforms inside a WebGL shader source string, not CSS, and a custom
 * property cannot cross into a shader. Everything else must be a var().
 */
const HEX = /#[0-9a-fA-F]{3,8}\b/g;
const hexHits: string[] = [];
for (const f of FILES) {
  if (f.rel === 'styles/theme.css' || f.rel === 'ui/Backdrop.tsx') continue;
  const body = f.body.replace(/&#\d+;/g, ''); // `&#215;` is the multiplication sign, not a colour
  for (const m of body.matchAll(HEX)) hexHits.push(`${f.rel}: ${m[0]}`);
}
hard('colour comes from tokens, not from hex literals', hexHits, 'a hardcoded colour cannot be themed');

/*
 * "Rectangles carry information. Cuts carry action." (UI-SPEC.md:18)
 * The chamfer is the app's whole surface grammar; a rounded corner is a
 * different system wearing the same clothes.
 */
const radiusHits: string[] = [];
for (const f of FILES) {
  for (const m of f.body.matchAll(/border-radius:\s*([^;\n]+)/g)) {
    const v = (m[1] ?? '').trim();
    if (!/^(0|0px|50%|9999px|var\(--radius-chrome\))$/.test(v)) radiusHits.push(`${f.rel}: ${v}`);
  }
}
hard('no border-radius outside the allowed set', radiusHits, 'this surface is cut, not rounded');

/*
 * THE CUT AND THE PLATES ARE NAMED ONCE, AND A COPY IS A REGRESSION.
 * ─────────────────────────────────────────────────────────────────
 * An inventory found the chamfer polygon declared as a literal in twenty-four
 * files, the plate backgrounds in thirteen, the gold rim pair in two and the
 * hairline rule in ten - none answering to a token, and the app's working
 * 10px cut in no scale at all. They now live in `theme.css` beside the cut
 * scale and are reached through `src/ui/geometry.ts`; the repoint was proved
 * pixel-identical by hashing the computed clip-path and background of every
 * plated element before and after (31 elements, same hash).
 *
 * This is HARD rather than a ratchet because the codebase is clean of them
 * today, and the whole value of the consolidation is that the spec's
 * stroke-bearing frame (UI-SPEC §2.0) has one place to land instead of
 * twenty-four. One re-typed polygon re-opens the twenty-fourth.
 */
const GEOMETRY_OWNERS = new Set(['styles/theme.css', 'ui/geometry.ts']);
/*
 * ONLY THE SIZES geometry.ts OWNS (8, 10, 14). `\d+px` was the first draft and
 * it flagged `app/Shell.tsx`, whose chip cuts are 4, 5, 6, 7 and 11px - a
 * micro-scale of the shell's own, not copies of the app's cut. Pointing an 11px
 * cut at the 10px token would have changed pixels to satisfy a rule about not
 * changing pixels. Those sizes are unowned debt to name, not regressions.
 */
const GEOMETRY_LITERALS: ReadonlyArray<[string, RegExp]> = [
  /*
   * BOTH ORIENTATIONS, ANY SPACING. A review showed the first regex caught only
   * the top-right/bottom-left shape with canonical spaces, so the frame's own
   * top-left/bottom-right polygon - or `polygon(0 0,calc(` - re-typed at an
   * owned size sailed through.
   */
  [
    'chamfer polygon',
    /polygon\(\s*(?:0 0,\s*calc\(100% - (?:8|10|14)px\) 0,\s*100% (?:8|10|14)px|(?:8|10|14)px 0,\s*100% 0,\s*100% calc\(100% - (?:8|10|14)px\))/,
  ],
  ['plate lift', /oklch\(1 0 0 \/ 0\.028\)/],
  ['cool plate', /linear-gradient\(168deg, oklch\(0\.16 0\.024 268/],
  /*
   * THE FULL VALUE, NOT A PREFIX. A prefix match called IntrinsicsPanel's rim
   * a copy; it is a variant (alpha 0.16 at 44%, against 0.18 at 42%) with no
   * comment saying why. That is drift worth naming, but unifying it here would
   * change pixels to satisfy a rule about not changing pixels. Only an exact
   * copy of the token's value is a regression.
   */
  ['gold rim', /linear-gradient\(150deg, var\(--color-orokin-400\), oklch\(0\.83 0\.105 90 \/ 0\.18\) 42%, transparent 78%\)/],
  ['hairline rule', /linear-gradient\(90deg, var\(--hairline\), transparent\)/],
];
const geometryHits: string[] = [];
for (const f of FILES) {
  if (GEOMETRY_OWNERS.has(f.rel.replace(/\\/g, '/'))) continue;
  const body = stripComments(f.body);
  for (const [what, re] of GEOMETRY_LITERALS) {
    if (re.test(body)) geometryHits.push(`${f.rel}: ${what} re-typed instead of imported from ui/geometry`);
  }
}
hard('the cut and the plates come from ui/geometry, never re-typed', geometryHits, 'a copied polygon is one more place the frame has to land');

/*
 * PROSE IS NEVER SET BELOW --text-small.
 * ─────────────────────────────────────
 * The fifth quality measurement put 79% of all type in the bottom three steps
 * of a nine-times scale, and the reason "nothing can be primary" turned out to
 * be concrete: fifty-six PARAGRAPHS were set at nano or micro - the label
 * sizes - in the faintest ink. Not fine print. "Rows past the cut say 'not
 * priced' rather than showing a zero - they were never quoted, which is a
 * different fact from being worth nothing" is this app's whole doctrine, and it
 * was 12px. `chain.blockedBy.note` - why a rate cannot be computed - was 12px.
 * `route.how` - what you actually do - was 13px. The information the owner
 * said was missing was all there, at the one size that cannot be read as
 * information.
 *
 * Two things a <p> can be that are not prose: a numeric caption (a label
 * wearing a paragraph tag) and a flex container of buttons. Both keep their
 * size; everything else is at least small. HARD, because the tree is clean of
 * it now and a sentence sinking back to caption size is exactly a regression.
 */
const PROSE_TAG = /<p\b[^>]*?>/gs;
const proseHits: string[] = [];
for (const f of FILES) {
  if (!f.rel.endsWith('.tsx')) continue;
  const body = stripComments(f.body);
  for (const m of body.matchAll(PROSE_TAG)) {
    const cls = /className="([^"]*)"/.exec(m[0])?.[1] ?? '';
    if (!/text-\[length:var\(--text-(?:nano|micro)\)\]/.test(cls)) continue;
    if (/\bnumeric\b|\bflex\b/.test(cls)) continue;
    const line = body.slice(0, m.index).split('\n').length;
    proseHits.push(`${f.rel}:${String(line)}: a paragraph at label size`);
  }
}
hard('prose is never set below --text-small', proseHits, 'a sentence at caption size cannot be read as information');

/*
 * EVERY CUSTOM PROPERTY REFERENCED MUST BE DEFINED, and this is a HARD rule
 * because the failure is silent in both directions.
 *
 * `var(--color-blood-400)` was used four times in one panel for "this went
 * down". The token does not exist. As a `color` the declaration is invalid and
 * the element inherits, so the number renders in ordinary ink and looks
 * entirely deliberate while carrying none of the meaning it was written to
 * carry. As an SVG `stroke` the property resolves to nothing and the line is
 * not drawn at all - which is how it was finally noticed, by looking at a
 * picture with a missing line in it.
 *
 * Neither the type checker, the linter, the build nor any other gate here can
 * see it. A misspelt token is indistinguishable from a deliberate one at every
 * stage except the render.
 */
const DEFINED = new Set<string>();
for (const f of FILES) {
  if (!f.rel.endsWith('.css')) continue;
  for (const m of f.body.matchAll(/^\s*(--[a-z0-9-]+)\s*:/gm)) DEFINED.add(m[1]!);
}
/*
 * Properties a component declares on itself and reads back through the cascade
 * - `--notch`, `--frame-edge`, `--i`, the pointer tracker's `--mx` family. They
 * are set in TSX rather than in a stylesheet, so a stylesheet scan cannot see
 * them and their absence here is not a defect.
 */
const SELF_SET = new Set<string>();
for (const f of FILES) {
  // Both spellings: `'--x':` and the computed-key `['--x' as string]:` the
  // transit chart uses, which the plain form does not see.
  for (const m of f.body.matchAll(/'(--[a-z0-9-]+)'(?:\s+as\s+string)?\s*\]?\s*:/g)) SELF_SET.add(m[1]!);
  for (const m of f.body.matchAll(/setProperty\(\s*'(--[a-z0-9-]+)'/g)) SELF_SET.add(m[1]!);
  for (const m of f.body.matchAll(/@property\s+(--[a-z0-9-]+)/g)) SELF_SET.add(m[1]!);
}

const undefinedTokens: string[] = [];
for (const f of FILES) {
  const body = stripComments(f.body);
  /*
   * A `var(--x, fallback)` is NOT relying on the token existing - the fallback
   * is the designed path for a property a component sets on itself. Only a
   * bare reference is a claim that something defines it.
   */
  for (const m of body.matchAll(/var\(\s*(--[a-z0-9-]+)\s*([,)])/g)) {
    if (m[2] === ',') continue;
    const token = m[1]!;
    if (DEFINED.has(token) || SELF_SET.has(token)) continue;
    const line = body.slice(0, m.index).split('\n').length;
    undefinedTokens.push(`${f.rel}:${String(line)}: var(${token}) is defined nowhere`);
  }
}
hard(
  'every custom property referenced is defined',
  [...new Set(undefinedTokens)],
  'an undefined token fails silently - text inherits, and SVG drops the property',
);

/* --------------------------------------------------------------- ratchet */

const TAILWIND_ROUNDED = /\brounded(?:-[a-z0-9]+)*\b/g;
let roundedCount = 0;
for (const f of FILES) roundedCount += [...stripComments(f.body).matchAll(TAILWIND_ROUNDED)].length;
/*
 * 3 - AND THE BASELINE FELL FROM 18 BECAUSE THE MEASUREMENT WAS WRONG, not
 * because fifteen corners were fixed. This counted `f.body` raw, and the
 * pattern's `-[a-z0-9]+` group is OPTIONAL, so it matched the bare English word
 * "rounded" wherever it appeared in a comment - including in this gate's own
 * prose about rounded corners, and in the chamfer doctrine written above it.
 * Sixteen of the eighteen were sentences. It fired the first time an unrelated
 * file used the word in a comment, which is how it was found.
 *
 * A ratchet that counts English holds nobody to anything: the number can be
 * paid down by deleting documentation and pushed up by explaining yourself.
 *
 * The three that remain are `rounded-full` on a status dot and a legend swatch.
 * A circle is not a rounded rectangle and the chamfer has nothing to say about
 * one, so this is probably its floor rather than a debt.
 */
ratchet('Tailwind rounded-* classes', roundedCount, 3, 'each one is a corner the chamfer should have cut');

let clipButton = 0;
for (const f of FILES) clipButton += [...f.body.matchAll(/--clip-button/g)].length;
ratchet('--clip-button references', clipButton, 4, 'the spec replaces the sheared parallelogram with --clip-hex');

/* ------------------------------------------------------ the cascade, capped */

/*
 * THE STAGGER IS COMPUTED, AND THE SPEC SAYS SO IN WORDS.
 * ————————————————————————————
 * `docs/research/ui-motion.md:206`: "Cap the total: stagger = min(0.035, 0.30 /
 * n). Compute it, do not hardcode it." It was hardcoded at 26ms a row, so the
 * eighteenth row began at 442ms - half again past the 300ms cap - and rows past
 * the eighteenth had no rule at all and began at 0, arriving BEFORE the rows
 * above them. Measured in the browser at 235 rows before and after: 442ms and
 * out of order, against 22.1ms and in order.
 *
 * Two things hold that: the delays must be expressed against the variable
 * rather than as fixed milliseconds, and the clamp past the eighteenth must
 * exist or the seam reopens silently.
 */
const motionCss = FILES.find((f) => f.rel === 'styles/theme.css')?.body ?? '';
const staged = [...motionCss.matchAll(/\.rf-staged > \*:nth-child\([^)]*\)\s*\{\s*animation-delay:\s*([^;]+);/g)].map(
  (m) => (m[1] ?? '').trim(),
);
hard(
  'the entrance cascade is computed, not hardcoded',
  staged.filter((v) => !v.includes('--rf-stagger')).map((v) => `animation-delay: ${v}`),
  'a fixed per-row delay cannot honour the 300ms cap on a long list',
);
hard(
  'the cascade has no backwards seam',
  motionCss.includes('.rf-staged > *:nth-child(n + 19)') ? [] : ['the nth-child(n + 19) clamp is gone'],
  'without it every row past the eighteenth starts at 0 and overtakes the rows above it',
);

/* ------------------------------------------------------ nesting, counted */

/*
 * HOW DEEP THE APP LETS A READER GO.
 * ————————————————————————————
 * `Disclosure` takes a `depth` and has always supported any value; the CSS
 * drives indent, rail opacity and now type size from it. The app used it at
 * depth 2 exactly ONCE across fourteen panels and at depth 3 never - measured
 * before this gate existed. Everything was one level: a reader could ask "how?"
 * a single time and then hit the floor.
 *
 * So the count of genuinely nested disclosures is a number with a direction,
 * and unlike the others here it must go UP. It is the most direct measure of
 * the thing the panels are missing, and it cannot be satisfied by nesting for
 * its own sake - a level with nothing under it is a level nobody opens twice.
 */
/*
 * COMMENTS ARE STRIPPED FIRST, AND THIS GATE FAILED ITS OWN TEST WITHOUT IT.
 *
 * The count was a plain text scan for `depth={N}`, so a house-style comment
 * explaining the pattern - and the comments in this codebase are long and quote
 * code constantly - counted as nesting. An agent rebuilding a panel hit exactly
 * that and reported a phantom extra level from a sentence.
 *
 * A gate that can be satisfied by describing the work instead of doing it is
 * worse than no gate: it reports the number everything else is measured
 * against. Block and line comments go before anything is counted.
 */
/*
 * A function declaration, not a const arrow: the geometry rule above uses it
 * before this line, and a `const` is in its temporal dead zone there - the
 * typecheck caught it, and at runtime Node threw before a single rule ran.
 */
function stripComments(body: string): string {
  return body.replace(/\/\*[\s\S]*?\*\//g, '').replace(new RegExp('//[^' + '\n' + ']*', 'g'), '');
}
const DEPTHS = [
  ...FILES.flatMap((f) => [...stripComments(f.body).matchAll(/depth=\{(\d+)\}/g)].map((m) => Number(m[1]))),
];
const deep = DEPTHS.filter((d) => d >= 2).length;

// Reported to the deepest depth actually present, not to a fixed four: a rung
// the instrument cannot print is a rung nobody will notice was added.
const deepest = DEPTHS.length > 0 ? Math.max(...DEPTHS) : 0;
const levels = Array.from({ length: deepest + 1 }, (_, d) => d);
report.push(`  nesting, by level:   ${levels.map((d) => `depth ${String(d)}: ${String(DEPTHS.filter((x) => x === d).length)}`).join(' · ')}`);

// FLOOR, not a ceiling: this one may rise and may not fall. 9 today, from 3
// before the worldstate rebuild and from 1 before `RelicTree`. Raised rather
// than left where it was, for the reason the number exists at all: a floor that
// sits under the measurement has stopped measuring, and the panels still built
// as a flat run of siblings are the ones it is here to name.
if (deep < 18) {
  failures += 1;
  report.push(`  FAIL  disclosures nested two or more levels deep - ${String(deep)} now, 18 required. Nesting was removed.`);
} else {
  report.push(`  ok    ${String(deep)} disclosures nested two or more deep (floor 18; raise it as panels are rebuilt)`);
}

/* ------------------------------------------------- the type scale, measured */

/*
 * THE MEASUREMENT THIS FILE EXISTS FOR.
 * ————————————————————————————————————————————
 * `theme.css` defines eight type steps from 0.75rem to 6.8rem - a 9x range,
 * a real scale. Measured in the running app at 1500x940, 88% of the visible
 * characters sat at 12.7px, 14px or 16.3px: the bottom three steps, spanning
 * 1.28x. `--text-mega` had never been used once and `--text-body`, the BODY
 * size, appeared sixteen times in the entire application.
 *
 * That is not a stylistic quibble. A scale used only at its bottom cannot
 * express hierarchy, so hierarchy gets faked with uppercase and letterspacing -
 * measured at 51% of visible text - and a label treatment applied to half the
 * screen stops meaning "label". The reader is then given no way in, which is
 * what "too messy, and somehow not enough information" is made of.
 *
 * So the share is a first-class number with a direction. It may fall.
 */
const STEPS = ['nano', 'micro', 'small', 'body', 'lead', 'title', 'hero', 'mega'] as const;
const uses = new Map<string, number>();
for (const step of STEPS) {
  let n = 0;
  /*
   * ROLES COUNT AS THE STEP THEY SET. `.wf-prose` is `--text-body` and
   * `.wf-note` is `--text-small`, declared once in theme.css - so a paragraph
   * wearing the role has no size class, and a counter that reads only
   * `var(--text-*)` stopped seeing forty-two paragraphs the moment they were
   * given a name. The share would have read as an improvement it had not
   * measured. Counted here, in the same units, so the number keeps meaning
   * what it did before the roles existed.
   */
  if (step === 'body' || step === 'small') {
    const role = step === 'body' ? 'wf-prose' : 'wf-note';
    for (const f of FILES) {
      if (f.rel === 'styles/theme.css') continue;
      n += [...f.body.matchAll(new RegExp(`\\b${role}\\b`, 'g'))].length;
    }
  }
  for (const f of FILES) {
    if (f.rel === 'styles/theme.css') continue;
    n += [...f.body.matchAll(new RegExp(`var\\(--text-${step}\\)`, 'g'))].length;
  }
  uses.set(step, n);
}
const bottom = (uses.get('nano') ?? 0) + (uses.get('micro') ?? 0) + (uses.get('small') ?? 0);
const total = [...uses.values()].reduce((a, b) => a + b, 0);
const share = total === 0 ? 0 : Math.round((100 * bottom) / total);

report.push('');
report.push(`  type scale, by use:  ${STEPS.map((s) => `${s} ${String(uses.get(s) ?? 0)}`).join(' · ')}`);

ratchet(
  'share of type in the bottom three steps',
  share,
  // 72. Lowered four times from the 82 measured at the start of the rebuild -
  // each drop is a panel that stopped setting its answers at caption size. The
  // largest single fall, 79 -> 72, was not a panel at all: it was naming the
  // two prose roles, so that a sentence stopped being dressed by hand at
  // whatever size its row happened to be.
  72,
  'a 9x scale spent inside its bottom 1.28x cannot carry hierarchy',
);

/*
 * `--text-mega` was defined and never used, which is a scale step that exists
 * only in the stylesheet. Either something is the biggest thing on its screen
 * or the step should not be there; both are fine and "neither" is not.
 */
ratchet('unused type steps', STEPS.filter((s) => (uses.get(s) ?? 0) === 0).length, 1, 'a step nothing uses is not a scale');

/*
 * NOTHING MAY START LARGER THAN IT ENDS, and this rule exists because of a
 * defect no other check in this repository could see.
 *
 * The slot outline reused the tick's keyframe, `am-tick`, which starts at
 * scale(1.55). On a 17 px tick that is a nine-pixel pop and it reads well. On
 * a 201 x 104 slot edge it starts at 311 x 161 - fifty-five pixels of dashed
 * gold hanging over the mod cards either side, for the first sixth of a second
 * of every single open.
 *
 * The types were right, the lint was clean, the settled screenshot was correct,
 * and all twenty-two swept UI states passed - because every one of them
 * measures the END of the animation. It took photographing the frames.
 *
 * So the rule is a blanket one, the way the reduced-motion rule is: in an
 * overlay whose whole job is to sit on somebody else's screen without covering
 * it, nothing may begin bigger than it finishes. Growing inward is always
 * available and always safe.
 */
const GROWS_OUTWARD: string[] = [];
/*
 * THE OVERLAY'S STYLESHEET ONLY. The rest of the app draws on its own window,
 * where an element overshooting its final size covers nothing that is not
 * already the app's - `theme.css`'s panel approach starts at 1.16 and is right
 * to. This rule is about drawing on somebody else's screen.
 */
for (const f of FILES.filter((x) => x.rel.endsWith('automod.css'))) {
  for (const [, name, body] of f.body.matchAll(/@keyframes\s+([\w-]+)\s*\{([\s\S]*?)\n\}/g)) {
    for (const [, arg] of (body ?? '').matchAll(/scale(?:X|Y|3d)?\(([^)]*)\)/g)) {
      for (const piece of (arg ?? '').split(',')) {
        const n = Number.parseFloat(piece.trim());
        if (Number.isFinite(n) && n > 1) GROWS_OUTWARD.push(`${f.rel}: @keyframes ${String(name)} starts at scale ${String(n)}`);
      }
    }
    /*
     * AND NO LEFTWARD TRAVEL, which is the same spill by a different property.
     * The overlay's own column is to the RIGHT of everything the game draws,
     * and its slot plates sit between mod cards - so an entrance that moves
     * left starts on top of a neighbour. `am-arrive` was translateX(-14px) and
     * put every row of the aside over the game's last card for 220 ms. Vertical
     * travel is unrestricted: it stays inside the slot.
     */
    for (const [, arg] of (body ?? '').matchAll(/translateX\(([^)]*)\)/g)) {
      const n = Number.parseFloat((arg ?? '').trim());
      if (Number.isFinite(n) && n < 0) GROWS_OUTWARD.push(`${f.rel}: @keyframes ${String(name)} travels ${String(n)}px leftward, onto whatever is beside it`);
    }
  }
}
hard('no entrance starts larger than it ends', GROWS_OUTWARD, 'an overlay element bigger than its final size is covering the game while it settles');

/* ------------------------------------------------------------------ verdict */

for (const line of report) console.log(line);
console.log('');
assert.equal(failures, 0, `${String(failures)} design-system rule(s) broken`);
console.log('the design system holds, and the debt above is not growing');
